### ISSUE TITLE
Fails with extended DE characters

### ISSUE THREAD

**Issue by meehab** [mreinstein/node-red-contrib-alexa-verifier#2]
I have  an Amazon skill in production for UK, UK and DE

When users of the DE call an intent that includes a slot with a string that contains a character with an umlaut, the verifier node throws the following 3x errors to the Node-Red debug panel;

```
"error validating the alexa cert:certificate verification failed"
"Deprecated call to msg.res.status"
"Deprecated call to msg.res.json"
```

The first is linked to the Alexa-Verifier node itself. The second 2 are linked to the originating http input node.

I have not tried any additional extended characters but umlauts 100% trip up the verifier.

Assistance appreciated.

**Comment by mreinstein** [comment]
@meehab what version of `alexa-verifier` is installed?

**Comment by meehab** [comment]
Hi Mike

Thanks for the quick reply. I have v0.0.7

Peter

**Comment by mreinstein** [comment]
@meehab I meant, which version of `alexa-verifier` is installed? alexa-verifier@0.3.6 added a fix for unicode characters. Maybe you're not running the version that has this fix?

https://github.com/mreinstein/alexa-verifier/commit/e16ce2b6f65e9e2f2a9c3a0361105b1241688be7

**Comment by meehab** [comment]
Ah, ok. I'll check that tomorrow and revert. (Late here now). Thanks again.

**Comment by meehab** [comment]
@mreinstein 
That was the problem. I was on v0.2.0 of the alexa-verifier. Updated to v0.3.6 and had a DE tester confirm all is now working as it should. Should have checked that before posting an issue.

Apologies for the panic and thanks for the super-prompt assistance.

**Comment by mreinstein** [comment]
glad it worked out!
